import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font.normal]
family = "Iosevka Nerd Font"
# family = "BigBlue_Terminal_437TT Nerd Font"
style = "Regular"

[font]
size = 15

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

